### PR TITLE
Changes to setup and added bias-cov method

### PR DESCRIPTION
**Pull request by mayermelhem**
Don't know why there is so much insertions? Main changes: 
- Function to convert nominal, bias, and cov to mean and sd 
- removed duplicate line in setup that was preventing me to pip install -e ...

### CODE REVIEW

**Comment by ccaprani** [comment]
I don't know what "egg-info" is, but it could be system-specific. If it is something unrelated to the project, you should add it to your gitignore so it doesn't show up here. 

What is the function naming convention? Usual python would be `get_moments`. Is the name meaningful? And what about biases less than or greater than one? Should the function know if it is a resistance or load variable? It may need another argument. Be good to include this in the docstring.

**Comment by mayermelhem** [comment]
- egg-info appears to be a system thing for the installation: https://stackoverflow.com/questions/2051192/what-is-a-python-egg
- naming convention follows other methods and functions in pyre. 
- renamed to be more meaningful
- docstring updated to make things clear on its assumption on bias.

**Comment by mayermelhem** [comment]
Based on today's discussion, probably do not need `getMoments` / `getMoments_fromNominal` function. 
Instead, nominal and bias can be inputted using the following instantiation: 
`Distribution('name',*nom*bias*np.array([1,cov]))` 
`Normal('r',*nom*bias*np.array([1,cov]))` 
`Gumbel('s',*nom*bias*np.array([1,cov]))` 
etc...

Please advise/make the necessary changes for merging/ending this pull request

**Comment by ccaprani** [comment]
Can you add that as an example usage to the docs? Under 
pyre/doc/tutorial.rst 
Will close this PR then - thanks!

**Comment by mayermelhem** [comment]
Tutorial updated and function removed. Please merge to master if you are happy and then I will delete this branch.

**Comment by mayermelhem** [comment]
FYI: This pull request is still active.

**Comment by ccaprani** [comment]
Please remove the egg info files.

**Comment by mayermelhem** [comment]
> Please remove the egg info files.

It has been added to the gitignore already... did you want to physically removed them?

**Comment by ccaprani** [comment]
Yes - please remove from this PR.

**Comment by mayermelhem** [comment]
Close, **do not** merge, and delete this branch. Refer to other pull request for suggestions.

**Pull request closed without merging**
